routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//sitios publicos
Route::get('/', function () {
    return view('index');   //view('index');

})->name('index'); 

Route::get('/top10', function() {
	return view('information.top10');
})->name('top10');

Route::get('/compra', function() {
	return view('reservacion.view');
})->name('preview.buy');

Route::get('/contacto/', function(){
	return view('information.contact'); 
})->name('show.contacto');


Route::get('itinerario/add','ItinerariosController@consulta')->name('itinerario.filtro');
Route::post('itinerario/buscar','ItinerariosController@busqueda')->name('itinerario.buscar');
Route::post('itinerario/captura','ItinerariosController@guardar')->name('itinerario.guardar');
Route::post('itinerario/guardar/cliente','ItinerariosController@cliente')->name('itinerario.cliente');
Route::post('asientos/reserva', 'ItinerariosController@asiento')->name('itinerario.asientos');
Route::post('tarifas/nuevo', 'ItinerariosController@mostrar')->name('itinerario.tarifas');

Route::post('/enviar', [
	'uses'	=> 	'MailController@store',
	'as'	=>	'mail.store'
]);
 
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

   //ayuda :(

Route::middleware(['auth'])->group(function(){


//Aqui iran todas las rutas una vez que haya finalizado todo el proceso de creación del menu de usuarios, para ver el tipo de acceso. 
	//ADMINISTRADOR DE APLICACION
Route::resource('user', 'UsersController');
Route::get('user/{id}/destroy', [
		'uses'	=>	'UsersController@destroy',
		'as'	=>	'user.destroy'
	]);


Route::resource('roles', 'RolesController');
Route::get('roles/{id}/destroy', [
		'uses'	=>	'RolesController@destroy',
		'as'	=>	'roles.destroy'
	]);
Route::resource('permisos', 'PermissionsController');
Route::get('permisos/{id}/destroy', [
		'uses'	=>	'PermissionsController@destroy',
		'as'	=>	'permisos.destroy'
	]);

route::resource('paises','PaisesController');
Route::get('paises/{id}/destroy', [
		'uses'	=>	'PaisesController@destroy',
		'as'	=>	'paises.destroy'
	]);
route::resource('departamentos','DepartamentosController');
Route::get('departamentos/{id}/destroy', [
		'uses'	=>	'DepartamentosController@destroy',
		'as'	=>	'departamentos.destroy'
	]);


route::resource('municipios','MunicipiosController');
Route::get('municipios/{id}/destroy', [
		'uses'	=>	'MunicipiosController@destroy',
		'as'	=>	'municipios.destroy'
	]);


route::resource('ciudades','CiudadesController');
Route::get('ciudades/{id}/destroy', [
		'uses'	=>	'CiudadesController@destroy',
		'as'	=>	'ciudades.destroy'
	]);

//RUTAS de Administrador de aeropuertos
route::resource('aerolineas','AerolineasController');
Route::get('aerolineas/{id}/destroy', [
		'uses'	=>	'AerolineasController@destroy',
		'as'	=>	'aerolineas.destroy'
	]);
Route::resource('aeropuertos', 'AeropuertosController');
Route::get('aeropuertos/{id}/destroy', [
		'uses'	=>	'AeropuertosController@destroy',
		'as'	=>	'aeropuertos.destroy'	
	]);

Route::resource('zonas', 'ZonasController');
Route::get('zonas/{id}/destroy', [
		'uses'	=>	'ZonasController@destroy',
		'as'	=>	'zonas.destroy'	
	]);



//USUARIOS INACTIVO
//Administrador de la Aplicacion

//muesta los usuarios eliminados
Route::get('/deshabilitado', [
		'uses'	=>	'UsersController@inactivo',
		'as'	=>	'user.inactivo'
	]);

Route::get('{id}/habilitar',[
		'uses'	=> 'UsersController@habilitar',
		'as'	=>	'user.habilitar'
	]);
//Cambio de contraseña por parte del administrador
Route::get('/{id}/password', [
		'uses'	=>	'UsersController@password',
		'as'	=>	'admin.password']);
Route::post('/{id}/change', [
        'uses'	=>	'UsersController@changepassword',
        'as'	=>	'admin.changepassword']);

//Cambiar de contraseña por parte del usuario
Route::get('/changepassword', [
		'uses'	=> 'UsersController@passwordchange',
		'as' 	=>	'user.password'
	]);
//guarda el cambio de contraseña
Route::post('/updatepassword', [
		'uses'	=>	'UsersController@updatepassword',
		'as'	=>	'user.updatepassword'
	]);	
 Route::resource('aviones', 'AvionesController');
 Route::get('aviones/{id}/destroy', [
		'uses'	=>	'AvionesController@destroy',
		'as'	=>	'aviones.destroy'	
	]);

 Route::resource('marcas', 'MarcasController');
 Route::get('marcas/{id}/destroy', [
		'uses'	=>	'MarcasController@destroy',
		'as'	=>	'marcas.destroy'	
	]);

 Route::resource('modelos', 'ModelosController');
 Route::get('modelos/{id}/destroy', [
		'uses'	=>	'ModelosController@destroy',
		'as'	=>	'modelos.destroy'	
	]);

 Route::resource('clases', 'ClasesController');
 Route::get('clases/{id}/destroy', [
		'uses'	=>	'ClasesController@destroy',
		'as'	=>	'clases.destroy'	
	]);

//vuelos
Route::resource('vuelos','VuelosController');
Route::get('vuelo/{id}/destroy', [
		'uses'	=>	'VuelosController@destroy',
		'as'	=>	'vuelos.destroy'
	]);
Route::get('/vuelos/create/tarifas',[
		'uses'	=>	'VuelosController@tarifas',
		'as'	=>	'vuelos.tarifas'
	]);
Route::get('/tarifas/create', [
		'uses'	=>	'VuelosController@asignacion',
		'as'	=>	'tarifas.create'
	]);
Route::post('/tarifas', [
		'uses'	=>	'VuelosController@guardar',
		'as'	=>	'tarifas.store'
	]);
});


 

app/User.php
<?php

namespace App;

use Caffeinated\Shinobi\Traits\ShinobiTrait;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;


class User extends Authenticatable
{
    use Notifiable;
    use ShinobiTrait { restore as private restoreA; }
    use SoftDeletes { restore as private restoreB; }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
       public function restore()
    {
        $this->restoreA();
        $this->restoreB();
    }
    protected $table = "users";

    protected $fillable = [
         'nombre', 'apellido', 'name', 'email', 'password'
    ];

    public $timestamps=true;
    protected $dates = ['deleted_at'];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function user(){
        return $this->hasOne('App\Cliente');
    }


}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Caffeinated\Shinobi\Models\Role;
use Validator;
use Auth;
use Hash;
use Laracasts\Flash\Flash;
class UsersController extends Controller
{
    //

	public function __construct(){

       	$this->middleware('permission:user.index')->only('index');
        $this->middleware('permission:user.edit')->only(['edit', 'update']);
        $this->middleware('permission:user.show')->only('show');
        $this->middleware('permission:user.destroy')->only('destroy');
        $this->middleware('permission:user.inactivo')->only('inactivo');
        $this->middleware('permission:user.habilitar')->only('habilitar');
        $this->middleware('permission:admin.password')->only(['password', 'changepassword']);

        
    }



    public function index(){

    	$user = User::orderBy('id', 'DESC')->get();
        $id = Auth::id();
    	return view('user.index')->with('user', $user)->with('id', $id);

    }

   public function edit($id){


   		$roles = Role::get();
    	$user = User::find($id);
        $rol= $user->roles->pluck('id')->ToArray();
        //dd($rol);

    	return view('user.edit', compact('user', 'roles', 'rol'));
    }

    public function update(Request $request, $id){
        $this->validate($request, [
            'nombre'  => 'required',
            'apellido'  => 'required',
            'usuario' => 'required|max:255',
            'roles'    => 'required'
        ]);
        
       
    	//actualiza primero al usuario
    	//segundo se actualiza al rol

    	//actualiza el usuario
    	$user = User::find($id);
    	$user->nombre = $request->nombre;
    	$user->apellido = $request->apellido;
    	$user->name = $request->usuario;
    	$user->update();

    	//actualizar role
    	$user->roles()->sync($request->get('roles'));
        flash("¡Se ha editado el usuario " . $user->name . " de forma exitosa")->warning()->important();
    	return redirect()->route('user.index');
    }

    public function show($id){

    	$user = User::find($id);

        $roles = Role::join("role_user","role_user.role_id","=","roles.id")
            ->where("role_user.user_id",$id)
            ->get();

    	return view('user.show', compact('user', 'roles'));
    }

    public function destroy($id){

   
		$user = User::find($id);
		$user->delete();
        flash("¡Se ha eliminado el usuario " . $user->name . " de forma exitosa")->error()->important();
		return redirect()->route('user.index');

    }


    public function inactivo(Request $request){

        $users = User::onlyTrashed()->get();
        return view('user.inactivo')->with('users', $users);

    }

    public function habilitar($id){

        $user = User::onlyTrashed()->where('id', $id)->restore();
        $user = User::find($id);
        return redirect()->route('user.index');
    }


    public function password($id){

        $user = User::find($id);
        return view('user.password')->with('user', $user);
    }

    public function changepassword(Request $request, $id){
        $this->validate($request, [
            'contraseña'           => 'required|string|min:8',
            'confirmar_contraseña' => 'required|same:contraseña|min:8',
        ]);
        $user = User::find($id);
        
        //dd($user);
        $user->password = bcrypt($request->contraseña);
        $user->save();
        flash("¡Se ha editado la contraseña " . $user->name . " de forma exitosa")->warning()->important();
        return redirect()->route('user.index');

    }

    public function passwordchange(){

        return view('user.newpassword');
    }


    public function updatepassword(Request $request){

        $this->validate($request, [
            'contraseña_actual'             => 'required',
            'contraseña_nueva'              => 'required|string|min:8',
            'confirmar_contraseña'          => 'required|same:contraseña_nueva|min:8',
        ]);
      

     if (Hash::check($request->contraseña_actual, Auth::user()->password)){
        $user = new User;
        $user->where('email', '=', Auth::user()->email)
             ->update(['password' => bcrypt($request->contraseña_nueva)]);
        flash("¡La contraseña ha sido modificada exitosamente!")->success()->important();
          Auth::logout();
        return redirect()->route('index');

        
        }
    else
        {
        
       
       flash('¡ERROR! ¡La contraseña ingresada no coincide con nuestros datos!')->error()->important();
        return back()->withInput();
        }

}
    
     
}

resources/views/user/rol/create.blade.php
@extends('layouts.template')
@section('content')
 @extends('layouts.errores')
<div class="span8" style="margin-left: 20%">
 <!-- Despliega mensajes de error -->
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                              <button type="button" class="close" data-dismiss="alert">
                                &times;</button>
                                <strong>¡ERROR!</strong> Hay errores en la información ingresada.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
@endif

<h1 style="align-content: left">Crear Roles</h1>
	<form action="{{ route('roles.store') }}" method="post" role="form" class="contactForm">
    {{csrf_field()}}
              <div class="row">
                <div class="span8 form-group {{ $errors->has('nombre') ? ' has-error' : '' }}">
                  <input type="text" name="nombre" class="input-block-level" id="nombre" placeholder="Nombre" data-rule="minlen:4" data-msg="Please enter at least 4 chars" required />
                     <div class="validation">
                    @if ($errors->has('nombre'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('nombre') }}</strong>
                                    </span>
                    @endif
                  </div>
                </div>
                <div class="span8 form-group {{ $errors->has('url') ? ' has-error' : '' }}">
                  <input type="text" name="url" class="input-block-level" id="url" placeholder="Url" data-rule="minlen:4" data-msg="Please enter at least 4 chars" required />
                    <div class="validation">
                    @if ($errors->has('url'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('url') }}</strong>
                                    </span>
                    @endif
                  </div>
                </div>
                <div class="span8 form-group">
                                    <textarea rows="4" cols="10" name="descripcion" id="descripcion" class="form-control" required></textarea>
                  </div>

                  <div align="left">
                    <h3>Permiso Especial</h3>
                  </div>
                   <div class="validation" align="left"></div>


                  <div class="span9 form-group ">
                    
                    <select class="span4 form-group" name="permiso_especial">
                      <option value="">Seleccionar Permiso Especial</option>
                    <option value="all-access">Acceso Total</option>
                    <option value="no-access">No acceso</option>
                    </select>
                    
                  </div>


                <div class="form-group" align="left">
                <h3>Asignar Privilegios</h3>
                </div>
                <div style="overflow: scroll; height: 300px">
                  <div class="span9 form-group {{ $errors->has('permisos') ? ' has-error' : '' }}" align="left">
                    <ul>
                      @foreach ($permisos as $permisos)
                    
                          <label>
                            <input  type="checkbox" value="{{$permisos->id }}" name="permisos[]">
                                         <strong>{{$permisos->name}}</strong><em>({{$permisos->description ?: 'Sin descripción'}})</em>
                            </label>
                          
                          @endforeach

                  </ul>
                  <div class="validation">
                    @if ($errors->has('permisos'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('permisos') }}</strong>
                                    </span>
                    @endif
                  </div>
                  </div>
                </div>

                  <div class="text-center span12" style="padding-top: 5%">
                    <button class="btn btn-primary" type="submit">Guardar</button>
                     <a href="{{route('roles.index')}}" class="btn btn-secondary" style="float:right 5%;"> <span>
                            <b>Cancelar</b></span></a>
                  </div>
                </div>
              </div>
            </form>
        </div>
              
@endsection

resources/views/user/rol/edit.blade.php
@extends('layouts.template')
@section('content')
<div class="span8" style="margin-left: 20%">
 <!-- Despliega mensajes de error -->
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                              <button type="button" class="close" data-dismiss="alert">
                                &times;</button>
                                <strong>¡ERROR!</strong> Hay errores en la información ingresada.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
@endif

<h1 style="align-content: left">Editar Roles</h1>
  <form class="form-horizontal" method="POST" action="{{route('roles.update', $roles->id )}}">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
              <div class="row">
                <div class="span8 form-group {{ $errors->has('nombre') ? ' has-error' : '' }}">
                  <input type="text" name="nombre" class="input-block-level" id="nombre" data-rule="minlen:4" value="{{ $roles->name}}" required />
                    <div class="validation">
                    @if ($errors->has('nombre'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('nombre') }}</strong>
                                    </span>
                    @endif
                  </div>
                </div>

                <div class="span8 form-group {{ $errors->has('url') ? ' has-error' : '' }}" style="padding-top: 2%">
                  <input type="text" name="url" class="input-block-level" id="url"  data-rule="minlen:4" value="{{ $roles->slug}}" required />
                  <div class="validation">
                    @if ($errors->has('url'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('url') }}</strong>
                                    </span>
                    @endif
                  </div>
                </div>
                <div class="span8 form-group {{ $errors->has('descripcion') ? ' has-error' : '' }}" style="padding-top: 2%">
                                    <textarea rows="4" cols="5" name="descripcion" id="descripcion" class="form-control" required>{{ $roles->description }}</textarea>
                                     <div class="validation">
                    @if ($errors->has('descripcion'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('descripcion') }}</strong>
                                    </span>
                    @endif
                  </div>
                  </div>
                  <div align="left">
                    <h3>Permiso Especial</h3>
                  </div>
                   <div class="validation" align="left"></div>

                  <br/>
                  <div class="span8 form-group">
                    
                      <select name="permiso_especial" class="span4 form-group">
                        <option @if(old('permiso_especial', $roles->special)== null) selected @endif>Selecciona Permiso Especial</option>
                        <option @if(old('permiso_especial', $roles->special)=='all-access') selected @endif>Acceso Total</option>
                        <option @if(old('permiso_especial', $roles->special)=='no-access') selected @endif>No acesso</option>
                      </select>
                  </div>
                   <div class="validation"></div>



                 <div class="form-group" align="left" style="padding-top: 7%">
                  <h3>Asignar Privilegios</h3>
                </div>

                <div style="overflow: scroll; height: 300px;" >
                  <div class="span9 form-group {{ $errors->has('permissions') ? ' has-error' : '' }}" align="left">
                <ul>
                                        @foreach($permisos as $permisos)
                                        <label>
                              <input type="checkbox" value="{{$permisos->id}}"
                                               {{in_array($permisos->id, $permission) ? "checked" : null}} name="permissions[]">
                                          {{$permisos->name}}</strong><em>({{$permisos->description ?: 'Sin descripción'}})</em>
                            </label>    
                                @endforeach
                                      </ul>
                                    </div>
                                    <div class="validation">
                    @if ($errors->has('permissions'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('permissions') }}</strong>
                                    </span>
                    @endif
                  </div>

                  <div class="validation"></div>
                  <div class="text-center">
                    <button class="btn btn-primary" type="submit">Guardar</button>
                     <a href="{{route('roles.index')}}" class="btn btn-secondary" style="float:right 5%;"> <span>
                            <b>Cancelar</b></span></a>
                  </div>
                </div>
              </div>
            </form>
        </div>
              
@endsection

resources/views/user/rol/index.blade.php
@extends('layouts.template')
@section('content')
 @extends('layouts.errores')
<div class="container" style="margin-top: 3%">
        <div class="col-md-9 col-md-offset-1">
            <div class="table-title" style=" margin-bottom: 1%">
                <div class="row">
                     <div class="col-sm-5" style="margin-left: 2%">

                        <h1 style="align-content: left">Gestion de Roles</h1>
                        @can('user.create')
                        <a href="{{ route('permisos.create')}}" class="btn btn-primary" style="float:right 5%;"> <span>
                            <b>Agregar Permisos</b></span></a>
                        @endcan
                     @can('roles.create')
                        <a href="{{ route('roles.create')}}" class="btn btn-primary" style="float:right 5%;"> <span>
                            <b>Agregar Roles</b></span></a>
                            @endcan
                         
                    </div>
                </div>
            </div>
            <table class="table table-striped table-hover" id="myTable" style="background: #fff;width: 100%">
                <thead>
                <tr>
                    <th>Nombres</th>
                    <th>Display Nombre</th>
                    <th>Descripcion</th>
                    <th width="23%">Acciones</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($roles as $role)
                <tr>
                    <td>{{ $role->name }}</td>
                    <td>{{ $role->slug}}</td>
                    <td>{{ $role->description }}</td> 
                    <td>
                        @can('roles.edit')
                        <a href="{{ route('roles.edit',$role->id)}}" class="btn btn-warning"><span class=" icon-pencil"></span> </a>
                        @endcan
                        @can('roles.show')
                        <a href="{{ route('roles.show', $role->id) }}" class="btn btn-primary"><span class="icon-eye-open"></span> </a>
                        @endcan
                        @can('roles.destroy')
                        <a style="margin-right: 3%" class="btn btn-danger" onclick="eliminar('{{ $role->id }}')"><span class="icon-trash"></span>
                    </a>
                    @endcan
                      </td>
                </tr>
                @endforeach
                </tbody>
            </table>
    
<!--Modal-->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-body">
                    <p> ¿Desea Eliminar? </p>
                    <input type="hidden">
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <a class="btn btn-danger" id="aceptar">Sí</a>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
<script>
    
    function eliminar(id){
        var iddentified=id;
        
        $('#exampleModal').modal();
        document.getElementById("aceptar").addEventListener("click", function() {
        var url ='{{ route("roles.destroy", ":id") }}';
        url=url.replace(":id",iddentified);
        window.location.href=url;
        }, false);

    }
    </script>
@endsection

resources/views/user/rol/show.blade.php
@extends('layouts.template')
@section('content')
<div class="span8">
<h1 style="align-content: left">Información del Rol</h1>
	
              <div class="row">
                <div class="panel-heading">Información del Rol {{ $role->name }}</div>

                    <div class="panel-body">
                        <div class="form-group">
                            <label for="name" class="col-md-4 control-label">Description</label>
                            <p>{{ $role->description}}</p>
                        </div>
                        <div class="span6 form-group">
                            <label for="name" class="col-md-4 control-label">Permisos</label>
                            @if(!empty($permission))
                                <div class="col-md-8 control-label">
                                
                                  @foreach($permission as $permission)
                              
                                       <p class="label label-info" style="float: left; margin-right: 5px">{{ $permission->name }}</p>

                                  @endforeach

                                </div>
                            @endif
                        </div>
</div>
              </div>
            </form>
        </div>
              
@endsection