routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//sitios publicos
Route::get('/', function () {
    return view('index');   //view('index');

})->name('index'); 

Route::get('/top10', function() {
	return view('information.top10');
})->name('top10');

Route::get('/compra', function() {
	return view('reservacion.view');
})->name('preview.buy');

Route::get('/contacto/', function(){
	return view('information.contact'); 
})->name('show.contacto');


Route::get('itinerario/add','ItinerariosController@consulta')->name('itinerario.filtro');
Route::post('itinerario/buscar','ItinerariosController@busqueda')->name('itinerario.buscar');
Route::post('itinerario/captura','ItinerariosController@guardar')->name('itinerario.guardar');
Route::post('itinerario/guardar/cliente','ItinerariosController@cliente')->name('itinerario.cliente');
Route::post('asientos/reserva', 'ItinerariosController@asiento')->name('itinerario.asientos');
Route::post('tarifas/nuevo', 'ItinerariosController@mostrar')->name('itinerario.tarifas');

Route::post('/enviar', [
	'uses'	=> 	'MailController@store',
	'as'	=>	'mail.store'
]);
 
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

   //ayuda :(

Route::middleware(['auth'])->group(function(){


//Aqui iran todas las rutas una vez que haya finalizado todo el proceso de creación del menu de usuarios, para ver el tipo de acceso. 
	//ADMINISTRADOR DE APLICACION
Route::resource('user', 'UsersController');
Route::get('user/{id}/destroy', [
		'uses'	=>	'UsersController@destroy',
		'as'	=>	'user.destroy'
	]);


Route::resource('roles', 'RolesController');
Route::get('roles/{id}/destroy', [
		'uses'	=>	'RolesController@destroy',
		'as'	=>	'roles.destroy'
	]);
Route::resource('permisos', 'PermissionsController');
Route::get('permisos/{id}/destroy', [
		'uses'	=>	'PermissionsController@destroy',
		'as'	=>	'permisos.destroy'
	]);

route::resource('paises','PaisesController');
Route::get('paises/{id}/destroy', [
		'uses'	=>	'PaisesController@destroy',
		'as'	=>	'paises.destroy'
	]);
route::resource('departamentos','DepartamentosController');
Route::get('departamentos/{id}/destroy', [
		'uses'	=>	'DepartamentosController@destroy',
		'as'	=>	'departamentos.destroy'
	]);


route::resource('municipios','MunicipiosController');
Route::get('municipios/{id}/destroy', [
		'uses'	=>	'MunicipiosController@destroy',
		'as'	=>	'municipios.destroy'
	]);


route::resource('ciudades','CiudadesController');
Route::get('ciudades/{id}/destroy', [
		'uses'	=>	'CiudadesController@destroy',
		'as'	=>	'ciudades.destroy'
	]);

//RUTAS de Administrador de aeropuertos
route::resource('aerolineas','AerolineasController');
Route::get('aerolineas/{id}/destroy', [
		'uses'	=>	'AerolineasController@destroy',
		'as'	=>	'aerolineas.destroy'
	]);
Route::resource('aeropuertos', 'AeropuertosController');
Route::get('aeropuertos/{id}/destroy', [
		'uses'	=>	'AeropuertosController@destroy',
		'as'	=>	'aeropuertos.destroy'	
	]);

Route::resource('zonas', 'ZonasController');
Route::get('zonas/{id}/destroy', [
		'uses'	=>	'ZonasController@destroy',
		'as'	=>	'zonas.destroy'	
	]);



//USUARIOS INACTIVO
//Administrador de la Aplicacion

//muesta los usuarios eliminados
Route::get('/deshabilitado', [
		'uses'	=>	'UsersController@inactivo',
		'as'	=>	'user.inactivo'
	]);

Route::get('{id}/habilitar',[
		'uses'	=> 'UsersController@habilitar',
		'as'	=>	'user.habilitar'
	]);
//Cambio de contraseña por parte del administrador
Route::get('/{id}/password', [
		'uses'	=>	'UsersController@password',
		'as'	=>	'admin.password']);
Route::post('/{id}/change', [
        'uses'	=>	'UsersController@changepassword',
        'as'	=>	'admin.changepassword']);

//Cambiar de contraseña por parte del usuario
Route::get('/changepassword', [
		'uses'	=> 'UsersController@passwordchange',
		'as' 	=>	'user.password'
	]);
//guarda el cambio de contraseña
Route::post('/updatepassword', [
		'uses'	=>	'UsersController@updatepassword',
		'as'	=>	'user.updatepassword'
	]);	
 Route::resource('aviones', 'AvionesController');
 Route::get('aviones/{id}/destroy', [
		'uses'	=>	'AvionesController@destroy',
		'as'	=>	'aviones.destroy'	
	]);

 Route::resource('marcas', 'MarcasController');
 Route::get('marcas/{id}/destroy', [
		'uses'	=>	'MarcasController@destroy',
		'as'	=>	'marcas.destroy'	
	]);

 Route::resource('modelos', 'ModelosController');
 Route::get('modelos/{id}/destroy', [
		'uses'	=>	'ModelosController@destroy',
		'as'	=>	'modelos.destroy'	
	]);

 Route::resource('clases', 'ClasesController');
 Route::get('clases/{id}/destroy', [
		'uses'	=>	'ClasesController@destroy',
		'as'	=>	'clases.destroy'	
	]);

//vuelos
Route::resource('vuelos','VuelosController');
Route::get('vuelo/{id}/destroy', [
		'uses'	=>	'VuelosController@destroy',
		'as'	=>	'vuelos.destroy'
	]);
Route::get('/vuelos/create/tarifas',[
		'uses'	=>	'VuelosController@tarifas',
		'as'	=>	'vuelos.tarifas'
	]);
Route::get('/tarifas/create', [
		'uses'	=>	'VuelosController@asignacion',
		'as'	=>	'tarifas.create'
	]);
Route::post('/tarifas', [
		'uses'	=>	'VuelosController@guardar',
		'as'	=>	'tarifas.store'
	]);
});


 

app/Avion.php
<?php

namespace App;
use Illuminate\Database\Query\Builder\withPivot;  
use Illuminate\Database\Eloquent\Model;

class Avion extends Model
{
     protected $table="aviones";

    protected $fillable = [ 'modelo_id','aerolinea_id','tipo_avion'];

    public $timestamps=true; 


    public function modelo(){ 
        return $this->belongsTo('App\Modelo', 'modelo_id');
    }

   /* public function clase(){ 
        return $this->belongsTo('App\Clase');
    }*/ 

    public function aerolinea(){ 
        return $this->belonsTo('App\Aerolinea');
    }

      public function clase(){
        //return $this->belongsToMany('App\Clase','avion_clase','avion_id','clase_id', 'numero_asiento');

      return $this->belongsToMany('App\Clase')->withPivot('id','fila', 'columna');
    }

    public function avionVuelo(){

      return $this->hasMany('App\VueloAvion');
    }
 
}

resources/views/avion/create.blade.php
@extends('layouts.template')
@section('content')
<div class="span12">
       <!-- Despliega mensajes de error -->
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                              <button type="button" class="close" data-dismiss="alert">
                                &times;</button>
                                <strong>¡ERROR!</strong> Hay errores en la información ingresada.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
@endif
<h1>Agregar Avion</h1>

  <form  name="asientos" action="{{route('aviones.store')}}" method="post" role="form" class="contactForm">
    {{csrf_field()}}

    <div class="span4 form-group {{ $errors->has('tipo_avion') ? ' has-error' : '' }}">
                  <input type="text" name="tipo_avion" class="input-block-level" id="tipo_avion" placeholder="Tipo de Avion" data-rule="minlen:4" data-msg="Please enter at least 4 chars" required />
                    <div class="validation">
                    @if ($errors->has('tipo_avion'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('tipo_avion') }}</strong>
                                    </span>
                    @endif
                  </div>

                </div> 
             <div class="span3 {{ $errors->has('modelos') ? ' has-error' : '' }}">
                    <select name="modelos" id="modelos" class="form-group" required>
                       <option value="">Seleccion Modelo</option>
                        @foreach($modelo as $model)
                          <option value="{{$model->id}}">{{$model->nombre_modelo}} </option>
                      @endforeach
                    </select>
                      <div class="validation">
                    @if ($errors->has('modelos'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('modelos') }}</strong>
                                    </span>
                    @endif
                  </div>
             </div>
               <div class="span3 {{ $errors->has('aerolinea') ? ' has-error' : '' }}">
                    <select name="aerolinea" class="form-group" required>
                       <option value="">Seleccion Aerolinea</option>
                       @foreach($aerolinea as $aerolineas)
                          <option value="{{$aerolineas->id}}">{{$aerolineas->nombre_aerolinea}} </option>
                      @endforeach
                    </select>
                    <div class="validation">
                    @if ($errors->has('aerolinea'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('aerolinea') }}</strong>
                                    </span>
                    @endif
                  </div>
             </div>
                <div class="span11 form-group">
                  <label><h5>Clases</h5></label>
                </div>
                     <div class="span11 form-group {{ $errors->has('clases') ? ' has-error' : '' }}">
                                    @foreach ($clases as $clase)
                              
                        <input class="in-line" type="checkbox" id="clases" value="{{$clase->id}}" name="clases[]" /> <strong>{{$clase->nombre_clase}}</strong>                         
                                    @endforeach 
                                      <div class="validation">
                    @if ($errors->has('clases'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('clases') }}</strong>
                                    </span>
                    @endif
                  </div>                         
                      </div>
             <div class="span4 form-group" style="margin-left: 32%">

              @foreach($clases as $clase)
                  <label>Asiento de {{ $clase->nombre_clase}}</label>
                  <input type="number" name="fila[]" value="" class="input-block-level" placeholder="Numero de Filas"  />
                  <input type="number" name="columna[]" value="" class="input-block-level" placeholder="Numero de Columna"  />

                  @endforeach
                                </div> 

              <div class="row">
                <div class="span12 form-group">
                  <div class="text-center">
                    <button class="btn btn-primary" type="submit">Guardar</button>
                     <a href="{{route('aviones.index')}}" class="btn btn-secondary" style="float:right 5%;"> <span>
                            <b>Cancelar</b></span></a>
                  </div>
                </div>
              </div>            
            </form>
        </div>
              
@endsection





   

resources/views/avion/edit.blade.php
@extends('layouts.template')
@section('content')
<div class="span12">
  <div class="span12">
       <!-- Despliega mensajes de error -->
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                              <button type="button" class="close" data-dismiss="alert">
                                &times;</button>
                                <strong>¡ERROR!</strong> Hay errores en la información ingresada.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
@endif
<h1>Editar Avion</h1>

  <form  name="asientos" action="{{route('aviones.update', $avion->id)}}" method="post" role="form" class="contactForm">
    {{csrf_field()}}
    {{ method_field('PUT') }}


    <div class="span4 form-group {{ $errors->has('tipo_avion') ? ' has-error' : '' }}">
                  <input type="text" name="tipo_avion" class="input-block-level" id="name" placeholder="Tipo de Avion" data-rule="minlen:4" value="{{$avion->tipo_avion}}" data-msg="Please enter at least 4 chars" />
                  <div class="validation">
                    @if ($errors->has('tipo_avion'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('tipo_avion') }}</strong>
                                    </span>
                    @endif
                  </div>

                </div> 

            

             <div class="span3 {{ $errors->has('tipo_avion') ? ' has-error' : '' }}">
                    <select name="modelos" id="modelos" class="form-group" >
                       <option value="">Seleccion Modelo</option>
                        @foreach($modelos as $model)
                          <option value="{{$model->id}}" @if($model->id==$avion->modelo_id) selected ='selected' @endif >{{$model->nombre_modelo}}</option>
                      @endforeach
                    </select>
                    <div class="validation">
                    @if ($errors->has('tipo_avion'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('tipo_avion') }}</strong>
                                    </span>
                    @endif
                  </div>

             </div>

        

               <div class="span3 {{ $errors->has('aerolinea') ? ' has-error' : '' }}">
                    <select name="aerolinea" class="form-group" >
                       <option value="">Seleccion Aerolinea</option>
                       @foreach($aerolinea as $aerolineas)
                          <option value="{{$aerolineas->id}}" @if($aerolineas->id==$avion->aerolinea_id) selected = 'selected' @endif>{{$aerolineas->nombre_aerolinea}} </option>
                      @endforeach
                    </select>
                     <div class="validation">
                    @if ($errors->has('aerolinea'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('aerolinea') }}</strong>
                                    </span>
                    @endif
                  </div>
             </div>

             
                  <div class="span11 form-group">
                  <label><h5>Clases</h5></label>
                </div>
                     <div class="span11 form-group {{ $errors->has('clases') ? ' has-error' : '' }}">
                        @foreach ($clases as $clase)
                              
                        <input class="in-line" type="checkbox" id="clases" value="{{$clase->id}}" {{in_array($clase->id, $class) ? "checked" : null}} name="clases[]" /> <strong>{{$clase->nombre_clase}}</strong>
                                    @endforeach                          
                      </div>
                      <div class="validation">
                    @if ($errors->has('clases'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('clases') }}</strong>
                                    </span>
                    @endif
                  </div>
             </dvi>
            <div class="span4 form-group" style="margin-left: 32%">

              @foreach($avion->clase as $clase)
                  <label>Asiento de {{ $clase->nombre_clase}} </label>
                    <h4>Fila</h4>
                  <input type="number" name="fila[]" value="{{ $clase->pivot->fila }}" class="input-block-level" placeholder="Numero de Filas"  />
                  <h4>Columna</h4>
                  <input type="number" name="columna[]" value="{{ $clase->pivot->columna }}" class="input-block-level" placeholder="Numero de Columna"  />
                  @endforeach
                  <div class="validation"></div>
                </div> 

              <div class="row">
                <div class="span12 form-group">
                  <div class="text-center">
                    <button class="btn btn-primary" type="submit">Guardar</button>
                     <a href="{{route('aviones.index')}}" class="btn btn-secondary" style="float:right 5%;"> <span>
                            <b>Cancelar</b></span></a>
                  </div>
                </div>
              </div>            
            </form>
        </div>
              
@endsection

resources/views/avion/index.blade.php
@extends('layouts.template')
@section('content')
 @extends('layouts.errores')
<div class="container" style="margin-top: 3%">
        <div class="col-md-9 col-md-offset-1">
            <div class="table-title" style=" margin-bottom: 1%">
                <div class="row">
                    <div class="col-sm-5" style="margin-left: 2%">
                        <h1 style="align-content: left">Gestion de Avion</h1>
                        @can('aviones.create')
                        <a href="{{route('aviones.create')}}" class="btn btn-primary" style="float:right 5%;"> <span><b>Agregar Avion</b></span></a>
                        @endcan
                    </div>
                </div>
            </div> 
            <div>
            <table class="table table-striped table-hover" id="myTable" style="width: 100%">
                <thead>
                <tr>
                    <th>Tipo de Avion</th>
                    <th>Modelo</th>
                    <th>Clase</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                @foreach($aviones as $avion)
                <tr>
                <td>{{$avion->tipo_avion}} </td>  
                <td>{{$avion->modelo->nombre_modelo}} </td>  
                <td> <ul>
                    @foreach($avion->clase as $clases)
                        <li>
                            {{$clases->nombre_clase}}
                        </li>
                      @endforeach
                    </ul>
                </td>
                  
                        <td>
                            @can('aviones.edit')
                        <a href="{{route('aviones.edit', $avion->id)}}" class="btn btn-warning"><span class=" icon-pencil"></span> </a>
                        @endcan
                        @can('aviones.destroy')
                        <a class="btn btn-danger" onclick="eliminar('{{ $avion->id }}')"><span class="icon-trash"></span>
                        </a>
                        @endcan
                      </td>
                </tr>
                 @endforeach
                </tbody>
            </table>
        </div>
         <!--Modal-->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-body">
                    <p> ¿Desea Eliminar? </p>
                    <input type="hidden">
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <a class="btn btn-danger" id="aceptar">Sí</a>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
<script>
    
    function eliminar(id){
        var iddentified=id;
        
        $('#exampleModal').modal();
        document.getElementById("aceptar").addEventListener("click", function() {
        var url ='{{ route("aviones.destroy", ":id") }}';
        url=url.replace(":id",iddentified);
        window.location.href=url;
        }, false);

    }
    </script>
@endsection