routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//sitios publicos
Route::get('/', function () {
    return view('index');   //view('index');

})->name('index'); 

Route::get('/top10', function() {
	return view('information.top10');
})->name('top10');

Route::get('/compra', function() {
	return view('reservacion.view');
})->name('preview.buy');

Route::get('/contacto/', function(){
	return view('information.contact'); 
})->name('show.contacto');


Route::get('itinerario/add','ItinerariosController@consulta')->name('itinerario.filtro');
Route::post('itinerario/buscar','ItinerariosController@busqueda')->name('itinerario.buscar');
Route::post('itinerario/captura','ItinerariosController@guardar')->name('itinerario.guardar');
Route::post('itinerario/guardar/cliente','ItinerariosController@cliente')->name('itinerario.cliente');
Route::post('asientos/reserva', 'ItinerariosController@asiento')->name('itinerario.asientos');
Route::post('tarifas/nuevo', 'ItinerariosController@mostrar')->name('itinerario.tarifas');

Route::post('/enviar', [
	'uses'	=> 	'MailController@store',
	'as'	=>	'mail.store'
]);
 
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

   //ayuda :(

Route::middleware(['auth'])->group(function(){


//Aqui iran todas las rutas una vez que haya finalizado todo el proceso de creación del menu de usuarios, para ver el tipo de acceso. 
	//ADMINISTRADOR DE APLICACION
Route::resource('user', 'UsersController');
Route::get('user/{id}/destroy', [
		'uses'	=>	'UsersController@destroy',
		'as'	=>	'user.destroy'
	]);


Route::resource('roles', 'RolesController');
Route::get('roles/{id}/destroy', [
		'uses'	=>	'RolesController@destroy',
		'as'	=>	'roles.destroy'
	]);
Route::resource('permisos', 'PermissionsController');
Route::get('permisos/{id}/destroy', [
		'uses'	=>	'PermissionsController@destroy',
		'as'	=>	'permisos.destroy'
	]);

route::resource('paises','PaisesController');
Route::get('paises/{id}/destroy', [
		'uses'	=>	'PaisesController@destroy',
		'as'	=>	'paises.destroy'
	]);
route::resource('departamentos','DepartamentosController');
Route::get('departamentos/{id}/destroy', [
		'uses'	=>	'DepartamentosController@destroy',
		'as'	=>	'departamentos.destroy'
	]);


route::resource('municipios','MunicipiosController');
Route::get('municipios/{id}/destroy', [
		'uses'	=>	'MunicipiosController@destroy',
		'as'	=>	'municipios.destroy'
	]);


route::resource('ciudades','CiudadesController');
Route::get('ciudades/{id}/destroy', [
		'uses'	=>	'CiudadesController@destroy',
		'as'	=>	'ciudades.destroy'
	]);

//RUTAS de Administrador de aeropuertos
route::resource('aerolineas','AerolineasController');
Route::get('aerolineas/{id}/destroy', [
		'uses'	=>	'AerolineasController@destroy',
		'as'	=>	'aerolineas.destroy'
	]);
Route::resource('aeropuertos', 'AeropuertosController');
Route::get('aeropuertos/{id}/destroy', [
		'uses'	=>	'AeropuertosController@destroy',
		'as'	=>	'aeropuertos.destroy'	
	]);

Route::resource('zonas', 'ZonasController');
Route::get('zonas/{id}/destroy', [
		'uses'	=>	'ZonasController@destroy',
		'as'	=>	'zonas.destroy'	
	]);



//USUARIOS INACTIVO
//Administrador de la Aplicacion

//muesta los usuarios eliminados
Route::get('/deshabilitado', [
		'uses'	=>	'UsersController@inactivo',
		'as'	=>	'user.inactivo'
	]);

Route::get('{id}/habilitar',[
		'uses'	=> 'UsersController@habilitar',
		'as'	=>	'user.habilitar'
	]);
//Cambio de contraseña por parte del administrador
Route::get('/{id}/password', [
		'uses'	=>	'UsersController@password',
		'as'	=>	'admin.password']);
Route::post('/{id}/change', [
        'uses'	=>	'UsersController@changepassword',
        'as'	=>	'admin.changepassword']);

//Cambiar de contraseña por parte del usuario
Route::get('/changepassword', [
		'uses'	=> 'UsersController@passwordchange',
		'as' 	=>	'user.password'
	]);
//guarda el cambio de contraseña
Route::post('/updatepassword', [
		'uses'	=>	'UsersController@updatepassword',
		'as'	=>	'user.updatepassword'
	]);	
 Route::resource('aviones', 'AvionesController');
 Route::get('aviones/{id}/destroy', [
		'uses'	=>	'AvionesController@destroy',
		'as'	=>	'aviones.destroy'	
	]);

 Route::resource('marcas', 'MarcasController');
 Route::get('marcas/{id}/destroy', [
		'uses'	=>	'MarcasController@destroy',
		'as'	=>	'marcas.destroy'	
	]);

 Route::resource('modelos', 'ModelosController');
 Route::get('modelos/{id}/destroy', [
		'uses'	=>	'ModelosController@destroy',
		'as'	=>	'modelos.destroy'	
	]);

 Route::resource('clases', 'ClasesController');
 Route::get('clases/{id}/destroy', [
		'uses'	=>	'ClasesController@destroy',
		'as'	=>	'clases.destroy'	
	]);

//vuelos
Route::resource('vuelos','VuelosController');
Route::get('vuelo/{id}/destroy', [
		'uses'	=>	'VuelosController@destroy',
		'as'	=>	'vuelos.destroy'
	]);
Route::get('/vuelos/create/tarifas',[
		'uses'	=>	'VuelosController@tarifas',
		'as'	=>	'vuelos.tarifas'
	]);
Route::get('/tarifas/create', [
		'uses'	=>	'VuelosController@asignacion',
		'as'	=>	'tarifas.create'
	]);
Route::post('/tarifas', [
		'uses'	=>	'VuelosController@guardar',
		'as'	=>	'tarifas.store'
	]);
});


 

app/Aeropuerto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Aeropuerto extends Model
{
    //
    protected $table = "aeropuertos";
    protected $fillable = ['nombre_aeropuerto', 'cod_aeropuerto', 'ciudad_id', 'telefono', 'nombre_responsable', 'apellido_responsable', 'numero_gateway', 'codigoarea_id'];

    public $timestamps = true;

    public function gateways()
    {
        return $this->hasMany('App\Gateway');
    }

    public function ciudad(){
    	return $this->belongsTo('App\Ciudad');
    }


    public function codigo(){
    	return $this->belongsTo('App\CodigoArea');
    }
}

app/Http/Controllers/AeropuertosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Ciudad;
use App\CodigoArea;
use App\Gateway;
use App\Aeropuerto;
use Laracasts\Flash\Flash;
use Illuminate\Support\Facades\DB;

class AeropuertosController extends Controller
{
    //

    function __construct()
    {
        $this->middleware('permission:aeropuertos.create')->only(['create', 'store']);
        $this->middleware('permission:aeropuertos.index')->only('index');
        $this->middleware('permission:aeropuertos.edit')->only(['edit', 'update']);
        $this->middleware('permission:aeropuertos.destroy')->only('destroy');
    }
    

    public function index(){

        $aeropuerto = Aeropuerto::all();
        $gateways = Gateway::all();
//            $aeropuerto = Aeropuerto::order_by('id','ASC')->get();
        return view('aeropuerto.index', compact('aeropuerto', 'gateways'));
    }

    public function create()
    {

        $ciudades = Ciudad::get();
        $codigos = CodigoArea::get();
        return view('aeropuerto.create',compact('codigos', 'ciudades'));
    }

    public function store(Request $request)
    {
         $this->validate($request, [
        'nombre_aeropuerto'      => 'required|max:50|unique:aeropuertos,nombre_aeropuerto',
        'ciudad'                 => 'required',
        'codigo_area'            => 'required',
        'telefono'               => 'required',
        'nombre_responsable'     => 'required|max:25',
        'apellido_responsable'   => 'required|max:25',
        'gateway'                => 'required'
        ]);

        $aeropuerto = new Aeropuerto();
        $aeropuerto->nombre_aeropuerto = $request->nombre_aeropuerto;
        $nom_aeropuerto = $request->nombre_aeropuerto;
        $aeropuerto->ciudad_id = $request->ciudad;
        $aeropuerto->codigoarea_id = $request->codigo_area;
        $aeropuerto->telefono = $request->telefono;
        $aeropuerto->nombre_responsable = $request->nombre_responsable;
        $aeropuerto->apellido_responsable = $request->apellido_responsable;
        $aeropuerto->numero_gateway = $request->gateway;
        $gate = $request->gateway;

        $words = explode(" ", $nom_aeropuerto);
        $initials = null;
        foreach ($words as $w) {
        $initials .= $w[0];
            }
        $aeropuerto->cod_aeropuerto = $initials;
        $aeropuerto->save();

        $ultimo_aeropuerto = DB::table('aeropuertos')->orderby('id', 'desc')->first();

        for ($i=1; $i<=$gate; $i++){

            $gateway = new Gateway();

            $gateway->aeropuerto_id = $ultimo_aeropuerto->id;
            $gateway->nombre_gateway = $initials."0".$i;
            $gateway->save();
        }

        flash("¡Se ha registrado el aeropuerto y gateways " .$aeropuerto->nombre_aeropuerto. " de forma exitosa!")->success()->important();

        return redirect()->action('AeropuertosController@index');

    }


    public function edit($id){

        $ciudades = Ciudad::all();
        $codigos = CodigoArea::all();
        $aeropuerto = Aeropuerto::find($id);
        return view('aeropuerto.edit', compact('aeropuerto', 'ciudades', 'codigos'));
    }

    public function update(Request $request, $id){
         $this->validate($request, [
       'nombre_aeropuerto'      => 'required|max:50|unique:aeropuertos,nombre_aeropuerto,' .$id,
        'ciudad'                 => 'required',
        'codigo_area'            => 'required',
        'telefono'               => 'required',
        'nombre_responsable'     => 'required|max:25',
        'apellido_responsable'   => 'required|max:25',
        'gateway'                => 'required'
        ]);

        $aeropuerto = Aeropuerto::find($id);
        $aeropuerto->nombre_aeropuerto = $request->nombre_aeropuerto;
        $nom_aeropuerto = $request->nombre_aeropuerto;
        $aeropuerto->ciudad_id = $request->ciudad;
        $aeropuerto->codigoarea_id = $request->codigo_area;
        $aeropuerto->telefono = $request->telefono;
        $aeropuerto->nombre_responsable = $request->nombre_responsable;
        $aeropuerto->apellido_responsable = $request->apellido_responsable;
        $aeropuerto->numero_gateway = $request->gateway;
        $gate = $request->gateway;

        $words = explode(" ", $nom_aeropuerto);
        $initials = null;
        foreach ($words as $w) {
        $initials .= $w[0];
            }
        $aeropuerto->cod_aeropuerto = $initials;
        $aeropuerto->update();

        DB::table('gateways')->where('aeropuerto_id', '=', $id)->delete();

        for ($i=1; $i<=$gate; $i++){

            $gateway = new Gateway();

            $gateway->aeropuerto_id = $id;
            $gateway->nombre_gateway = $initials."0".$i;
            $gateway->save();
        }

        flash("¡Se ha editado el aeropuerto y gateways " .$aeropuerto->nombre_aeropuerto. " de forma exitosa!")->warning()->important();

        return redirect()->action('AeropuertosController@index');

    }

    public function destroy($id){

        $aeropuerto = Aeropuerto::find($id);
        $aeropuerto->delete();

        DB::table('gateways')->where('aeropuerto_id', '=', $id)->delete();

        flash("¡Se ha eliminado el aeropuerto y gateways " .$aeropuerto->nombre_aeropuerto. " de forma exitosa!")->error()->important();

        return redirect()->action('AeropuertosController@index');
    }



}

app/Http/Controllers/ZonasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\CodigoArea;
use App\Pais;
use Validator;
use Laracasts\Flash\Flash;
class ZonasController extends Controller
{
    //
    public function __construct(){

        $this->middleware('permission:zonas.create')->only(['create', 'store']);
        $this->middleware('permission:zonas.index')->only('index');
        $this->middleware('permission:zonas.edit')->only(['edit', 'update']);
        $this->middleware('permission:zonas.destroy')->only('destroy');
        
    }

    public function index(){

    	$zonas = CodigoArea::orderBy('id', 'DESC')->get();
      	
       	return view('aeropuerto.zona.index')->with('zonas', $zonas);
      }

     public function create(){

     	$paises= Pais::get();
        
       return view('aeropuerto.zona.create', compact('paises')); 
    }


     public function store(Request $request){
        $this->validate($request, [
            'pais'  => 'required|unique:codigosareas,pais_id',
            'codigo_area'  => 'required|unique:codigosareas,codigo'
        ]);
        
   

     	$zonas = new CodigoArea();
     	$zonas->pais_id = $request->pais;
     	$zonas->codigo = $request->codigo_area;
     	$zonas->save();
        flash("¡Se ha registrado el codigo de area " . $zonas->codigo . " de forma existosa!")->success()->important();

     	return redirect()->action('ZonasController@index');
      
    }

     public function edit($id) {

     	$zona= CodigoArea::find($id);
     	$pais = Pais::all();

     	return view('aeropuerto.zona.edit')->with('zona', $zona)->with('pais', $pais);
         
    }

    public function update(Request $request, $id) { 

          $this->validate($request, [
            'pais'  => 'required|unique:codigosareas,pais_id,' .$id,
            'codigo_area'  => 'required|unique:codigosareas,codigo,' .$id
        ]);

         $zona = CodigoArea::find($id);
         $zona->pais_id=$request->pais;
         $zona->codigo=$request->codigo_area;
         $zona->update();
         flash("¡Se ha editado el codigo de area " . $zona->codigo . " de forma existosa!")->warning()->important();
         return redirect()->action('ZonasController@index');
      
    }

    public function destroy($id){ 
        
        $zona = CodigoArea::find($id);
        $zona->delete();
        flash("¡Se ha eliminado el codigo de area " . $zona->codigo . " de forma existosa!")->error()->important();
        return redirect()->action('ZonasController@index');
    
    }
}

resources/views/aeropuerto/zona/create.blade.php
@extends('layouts.template')
@section('content')
<div class="span6" style="margin-left: 25%">
  <!-- Despliega mensajes de error -->
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                              <button type="button" class="close" data-dismiss="alert">
                                &times;</button>
                                <strong>¡ERROR!</strong> Hay errores en la información ingresada.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
@endif
<h1>Agregar Zona</h1>

	<form action="{{ route('zonas.store') }}" method="post" role="form" class="contactForm">
    {{csrf_field()}}

              <div class="span5 {{ $errors->has('pais') ? ' has-error' : '' }}">
                    <select name="pais" class="form-group" required>
                       <option value="">Seleccion Pais</option>
                       @foreach($paises as $pais)
                       <option value="{{ $pais->id }}">{{$pais->nombre }}</option>
                       @endforeach
                    </select>
                    <div class="validation">
                    @if ($errors->has('pais'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('pais') }}</strong>
                                    </span>
                    @endif
                  </div>
             </div>
              <div class="row">
                <div class="span6 form-group {{ $errors->has('codigo_area') ? ' has-error' : '' }}">
                  <input type="text" name="codigo_area" class="input-block-level" id="codigo_area" placeholder="Codigo de Area" data-rule="minlen:3" required />
                  <div class="validation">
                    @if ($errors->has('codigo_area'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('codigo_area') }}</strong>
                                    </span>
                    @endif
                  </div>
                </div>
                <div class="span6 form-group">
                  <div class="text-center">
                    <button class="btn btn-primary" type="submit">Guardar</button>
                    <a href="{{route('zonas.index')}}" class="btn btn-secondary" style="float:right 5%;"> <span>
                            <b>Cancelar</b></span></a>
                  </div>
                </div>
              </div>
            </form>
        </div>
              
@endsection

resources/views/aeropuerto/zona/edit.blade.php
@extends('layouts.template')
@section('content')
<div class="span6" style="margin-left: 25%">
   <!-- Despliega mensajes de error -->
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                              <button type="button" class="close" data-dismiss="alert">
                                &times;</button>
                                <strong>¡ERROR!</strong> Hay errores en la información ingresada.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
@endif
<h1>Editar Zona</h1>
<form action="{{ route('zonas.update', $zona->id) }}" method="post" role="form" class="contactForm">
    {{csrf_field()}}
    {{ method_field('PUT') }}

              <div class="span5 {{ $errors->has('pais') ? ' has-error' : '' }}">
                    <select name="pais" class="form-group" required>
                       <option value="">Seleccion Pais</option>
                       @foreach($pais as $pais)
                          <option value="{{$pais->id}}" @if($pais->id==$zona->pais_id)
                            selected='selected' @endif>{{$pais->nombre}} </option>
                      @endforeach
                    </select>
                    <div class="validation">
                    @if ($errors->has('pais'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('pais') }}</strong>
                                    </span>
                    @endif
                  </div>
                  </div>
              <div class="row">
                <div class="span6 form-group {{ $errors->has('codigo_area') ? ' has-error' : '' }}">
                  <input type="text" name="codigo_area" class="input-block-level" id="codigo_area" value="{{ $zona->codigo }}" data-rule="minlen:3" required />
                  <div class="validation">
                    @if ($errors->has('codigo_area'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('codigo_area') }}</strong>
                                    </span>
                    @endif
                  </div>
                </div>
                <div class="span6 form-group">
                  <div class="text-center">
                    <button class="btn btn-primary" type="submit">Guardar</button>
                    <a href="{{route('zonas.index')}}" class="btn btn-secondary" style="float:right 5%;"> <span>
                            <b>Cancelar</b></span></a>
                  </div>
                </div>
              </div>
            </form>
        </div>
              
@endsection

resources/views/aeropuerto/zona/index.blade.php
@extends('layouts.template')
@section('content')
<div class="container" style="margin-top: 3%">
        <div class="col-md-9 col-md-offset-1">
            <div class="table-title" style=" margin-bottom: 1%">
                <div class="row">
                    <div class="col-sm-5" style="margin-left: 2%">
                        <h1 style="align-content: left">Gestion de Zonas</h1>
                        @can('zonas.create')
                        <a href="{{ route('zonas.create') }}" class="btn btn-primary" style="float:right 5%;"> <span><b>Agregar Zona</b></span></a>
                        @endcan
                    </div>
                </div>
            </div>
            <table class="table table-striped table-hover" id="myTable" style="background: #fff;width: 100%">
                <thead>
                <tr>
                    <th>Pais</th>
                    <th>Nombres</th>
                    <th width="23%">Acciones</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($zonas as $zona)
                <tr>
                    <td>{{ $zona->pais->nombre }}</td>
                    <td>{{ $zona->codigo }}</td> 
                        <td>
                            @can('zonas.edit')
                        <a href="{{ route('zonas.edit', $zona->id) }}" class="btn btn-warning"><span class=" icon-pencil"></span> </a>
                        @endcan
                        @can('zonas.destroy')
                        <a style="margin-right: 3%" class="btn btn-danger" onclick="eliminar('{{ $zona->id }}')"><span class="icon-trash"></span>
                            @endcan
                    </a>
                      </td>
                </tr>
                @endforeach
                </tbody>
            </table>
            <!--Modal-->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-body">
                    <p> ¿Desea Eliminar? </p>
                    <input type="hidden">
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <a class="btn btn-danger" id="aceptar">Sí</a>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
<script>
    
    function eliminar(id){
        var iddentified=id;
        
        $('#exampleModal').modal();
        document.getElementById("aceptar").addEventListener("click", function() {
        var url ='{{ route("zonas.destroy", ":id") }}';
        url=url.replace(":id",iddentified);
        window.location.href=url;
        }, false);

    }
    </script>
@endsection